FROM nginx:alpine
COPY web/dist /usr/share/nginx/html
COPY packages/chat-widget/dist/widget.js /usr/share/nginx/html/widget.js
COPY packages/chat-widget/dist/widget.css /usr/share/nginx/html/widget.css
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
